install:
	pnpm install

build:
	pnpm run docs:build

dev:
	pnpm run docs:dev

preview:
	pnpm run docs:preview

update:
	pnpm update

.PHONY: install update prepare build

prepare:
	pnpm run docs:prepare

